apiVersion: v1
kind: Pod
metadata:
  name: pod-nginx
spec:
  containers:
    - name: server-nginx
      image: nginx:alpine
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"