services:
  server-mysql:
    image: mysql:8
    container_name: server-mysql
    ports:
      - "3326:3306"
    env_file:
      - ./mysql/config/.env
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - ./mysql/data:/var/lib/mysql
    networks:
      - net-ms

  client-mysql:
    image: phpmyadmin:latest
    container_name: client-mysql
    ports:
      - "9080:80"
    environment:
      - PMA_ARBITRARY=1
    networks:
      - net-ms

  server-rabbitmq:
    image: rabbitmq:management-alpine
    container_name: server-rabbitmq
    ports:
      - "15672:15672" # Management UI
      - "5672:5672" # RabbitMQ
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - net-ms


  movie:
    image: movie
    build:
      context: ./apps/movie
      dockerfile: Dockerfile
    container_name: movie
    profiles:
      - apps
    ports:
      - "4500:3000"
    env_file:
      - ./config/database.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/healthcheck"]
      interval: 10s
      timeout: 20s
      retries: 2
    networks:
      - net-ms
    depends_on:
      server-mysql:
        condition: service_healthy

networks:
  net-ms:
    driver: bridge
    name: net-ms