apiVersion: v1
kind: Namespace
metadata:
  name: ns-dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-frontend-dev
  namespace: ns-dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
      env: dev
  template:
    metadata:
      labels:
        app: frontend
        env: dev
      namespace: ns-dev
    spec:
      containers:
        - name: app-frontend
          image: nginx:alpine
---
apiVersion: v1
kind: Namespace
metadata:
  name: ns-prd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-frontend-prd
  namespace: ns-prd
spec:
  replicas: 6
  selector:
    matchLabels:
      app: frontend
      env: prd
  template:
    metadata:
      labels:
        app: frontend
        env: prd
      namespace: ns-prd
    spec:
      containers:
        - name: app-frontend
          image: nginx:alpine