apiVersion: v1
kind: Secret
metadata:
  name: sc-database
type: Opaque
data:
  user: dXNlci1kaW9z
  pass: c3VwZXItcGFzc3dvcmQtMjAyNQ==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-frontend
spec:
  replicas: 5
  selector:
    matchLabels:
      app: frontend
      env: qa
  template:
    metadata:
      labels:
        app: frontend
        env: qa
    spec:
      containers:
        - name: app-frontend
          image: nginx:alpine
          env:
            - name: USER
              valueFrom:
                secretKeyRef:
                  name: sc-database
                  key: user
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sc-database
                  key: pass