export enum Genre {
    Action = 'Action',
    Adventure = 'Adventure',
    Animation = 'Animation',
    Biography = 'Biography',
    Comedy = 'Comedy',
    Crime = 'Crime',
    Drama = 'Drama',
    Family = 'Family',
    Fantasy = 'Fantasy',
    FilmNoir = 'Film Noir',
    History = 'History',
    Horror = 'Horror',
    Music = 'Music',
    Musical = 'Musical',
    Mystery = 'Mystery',
    Romance = 'Romance',
    SciFi = 'Sci-Fi',
    Sport = 'Sport',
    Superhero = 'Superhero',
    Thriller = 'Thriller',
    War = 'War',
    Western = 'Western'
}